name: Build & Deploy Docusaurus
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: just-another-blog
          git-user: cesarecaoduro
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages